using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web_Api.Models;

namespace Web_Api
{
    public class ApiDbContext:DbContext
    {
        
        public ApiDbContext(DbContextOptions<ApiDbContext> options) : base(options)
        {
        }
        

        public virtual DbSet<TestTable> TestTable { get; set; }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            //DbSets and classes generated by reverse-engineering
        }
    }
}
